### ISSUE TITLE
Synchronization Issue with Meraki Dashboard

### ISSUE THREAD

**Issue by pachecole** [meraki/adaptive-policy-ise-sync#21]
Hi
I've deployed it using docker latest version, but it don't sync with meraki dashboard:
![image](https://user-images.githubusercontent.com/104222392/168249537-e06dd4cb-d891-474b-a230-dd2cf53b0104.png)

The API key is correct and it can get the org ID and name:
![image](https://user-images.githubusercontent.com/104222392/168253955-091640d5-21b6-4c89-957b-617809681193.png)

When I select the SGT to sync it shows Meraki Missing:
![image](https://user-images.githubusercontent.com/104222392/168250328-92805335-40a4-4f89-8aff-cb7547aa3b19.png)

And in the console log it shows the following error::
Job "sync_dashboard (trigger: interval[0:00:30], next run at: 2022-05-13 09:05:28 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/app/adaptive_policy_sync/scripts/dashboard_monitor.py", line 334, in sync_dashboard
    ingest_dashboard_data(dbs, log)
  File "/opt/app/adaptive_policy_sync/scripts/dashboard_monitor.py", line 45, in ingest_dashboard_data
    sgpolicies = meraki_read_sgpolicy(dashboard, org_id)
  File "/opt/app/adaptive_policy_sync/scripts/meraki_addons.py", line 122, in meraki_read_sgpolicy
    return db._session.get(metadata, resource)
  File "/usr/local/lib/python3.7/site-packages/meraki/rest_session.py", line 268, in get
    response = self.request(metadata, 'GET', url, params=params)
  File "/usr/local/lib/python3.7/site-packages/meraki/rest_session.py", line 262, in request
    raise APIError(metadata, response)
meraki.exceptions.APIError: organizations, getOrganizationAdaptivePolicyBindings - 404 Not Found, <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtmplease wait a minute if the key or org was just newly created.

Also when I check the Match Report it shows:
![image](https://user-images.githubusercontent.com/104222392/168250811-d78f846e-b13a-43ca-b0f3-dff79e214cc3.png)
![image](https://user-images.githubusercontent.com/104222392/168250879-27339aa5-1f5d-47a9-bae5-28d22895ee1f.png)

Could you review that bug? Thanks in advance

**Comment by pachecole** [comment]
Hi
To rule out any issues with the API key, I've tested it at: https://developer.cisco.com/meraki/api-v1/#!create-organization-adaptive-policy-group and Postman and works correctly.
